= Prayers

== El silencio de este día
Señor,{zwsp} +
En el silencio de este día que nace, vengo a{zwsp} +
pedirte paz, sabiduría y fuerza.{zwsp} +
Hoy quiero mirar al mundo con ojos llenos de amor.{zwsp} +
Ser pacinte, comprensivo, humilde, suave y bueno.{zwsp} +
Ver a tus hijos detrás de las apariencias, como{zwsp} +
los ves tu mismo, para así poder apreciar{zwsp} +
la bondad de cada uno.{zwsp} +
Cierra mis oídos a toda murmuración.{zwsp} +
Guarda mi lengua de toda maledicencia.{zwsp} +
Que sólo los pensamientos que{zwsp} +
bendigan permanezcan en mi.{zwsp} +
Quiero ser tan bienintencionado{zwsp} +
y bueno que todos los que se{zwsp} +
acerquen a mi sientan tu presencia.{zwsp} +
Revísteme de tu bondad señor y haz{zwsp} +
que en este día yo te refleje.{zwsp} +

*Amén.*

== Oh Señora Mía
¡Oh Señora mía!{zwsp} +
¡Oh Madre mía!{zwsp} +
Yo me ofrezco enteramente a ti y en prueba de mi filial afecto te consagro en este día,{zwsp} +
mis ojos, mis oídos, mi lengua, mi corazón;{zwsp} +
en una palabra, todo mi ser.{zwsp} +
Ya que soy todo tuyo{zwsp} +
Oh Madre de bondad,{zwsp} +
guardame y defiéndeme como a pertenencia y posesión tuya. 

*Amén.*
