= Prayers

== El silencio de este día
Señor,{zwsp} +
En el silencio de este día que nace, vengo a{zwsp} +
pedirte paz, sabiduría y fuerza.{zwsp} +
Hoy quiero mirar al mundo con ojos llenos de amor.{zwsp} +
Ser pacinte, comprensivo, humilde, suave y bueno.{zwsp} +
Ver a tus hijos detrás de las apariencias, como{zwsp} +
los ves tu mismo, para así poder apreciar{zwsp} +
la bondad de cada uno.{zwsp} +
Cierra mis oídos a toda murmuración.{zwsp} +
Guarda mi lengua de toda maledicencia.{zwsp} +
Que sólo los pensamientos que{zwsp} +
bendigan permanezcan en mi.{zwsp} +
Quiero ser tan bienintencionado{zwsp} +
y bueno que todos los que se{zwsp} +
acerquen a mi sientan tu presencia.{zwsp} +
Revísteme de tu bondad señor y haz{zwsp} +
que en este día yo te refleje.{zwsp} +

*Amén.*

== Oh Señora Mía
¡Oh Señora mía!{zwsp} +
¡Oh Madre mía!{zwsp} +
Yo me ofrezco enteramente a ti y en prueba de mi filial afecto te consagro en este día,{zwsp} +
mis ojos, mis oídos, mi lengua, mi corazón;{zwsp} +
en una palabra, todo mi ser.{zwsp} +
Ya que soy todo tuyo{zwsp} +
Oh Madre de bondad,{zwsp} +
guardame y defiéndeme como a pertenencia y posesión tuya. 

*Amén.*

== Himno al Espíritu Santo
Espíritu SantoVen, Espíritu Divino,{zwsp} +
manda tu luz desde el cielo.{zwsp} +
Padre amoroso del pobre,{zwsp} +
don, en tus dones espléndido;{zwsp} +
luz que ilumina las almas{zwsp} +
fuente del mayor consuelo.{zwsp} +

Ven, dulce huésped del alma,{zwsp} +
descanso en nuestros esfuerzos,{zwsp} +
tregua en el duro trabajo,{zwsp} +
brisa en las horas de fuego,{zwsp} +
gozo que enjuga las lágrimas,{zwsp} +
y reconforta en los duelos.{zwsp} +

Llega hasta el fondo del alma{zwsp} +
Divina luz y enriquécenos.{zwsp} +
Mira el vacío del alma{zwsp} +
Si Tú le faltas por dentro.{zwsp} +
Mira el poder del pecado{zwsp} +
cuando no envías tu aliento.{zwsp} +

Riega la tierra en sequía.{zwsp} +
Sana el corazón enfermo.{zwsp} +
Lava las manchas. Infunde{zwsp} +
calor de vida en mi hielo.{zwsp} +
Doma al espíritu indómito,{zwsp} +
guía al que tuerce el sendero.{zwsp} +

Reparte tus siete dones{zwsp} +
según la fe de tus siervos.{zwsp} +
Por tu bondad y tu gracia{zwsp} +
dale al esfuerzo su éxito.{zwsp} +
Salva al que busca salvarse{zwsp} +
y danos tu gozo eterno. {zwsp} +

*Amén.*

== Dulce huésped del alma
Ven, Espíritu Divino, manda tu luz desde el cielo.{zwsp} +
Padre amoroso del pobre, don en tus dones espléndido;{zwsp} +
luz que penetra las almas, fuente del mayor consuelo.{zwsp} +

Ven, dulce huésped del alma, descanso de nuestro esfuerzo,{zwsp} +
tregua en el duro trabajo, gozo que enjuga las lágrimas{zwsp} +
y reconforta en los duelos.{zwsp} +

Entra hasta el fondo del alma, divina luz, y enriquécenos.{zwsp} +
Mira el vacío del hombre si tú le faltas por dentro.{zwsp} +
Mira el poder del pecado cuando no envías tu aliento.{zwsp} +

Riega la tierra en sequía, sana el corazón del enfermo;{zwsp} +
lava las manchas, infunde calor de vida en el hielo,{zwsp} +
doma el espíritu indómito, guía al que tuerce el sendero.{zwsp} +

Reparte tus siete dones, según la fe de tus siervos;{zwsp} +
por tu bondad y tu gracia, dale al esfuerzo su mérito;{zwsp} +
salva al que busca salvarse y danos tu gozo eterno.{zwsp} +

== La Más bella oración
Dios, dame el día de hoy fe para seguir adelante.{zwsp} +
Dame Grandeza de espírituo para perdonar.{zwsp} +
Dame paciencia para comprender y esperar.{zwsp} +
Dame voluntad para no caer.{zwsp} +
Dame fuerza para levantarme si caído estoy.{zwsp} +
Dame amor para dar.{zwsp} +
Dame lo que necesito y no lo que quiero.{zwsp} +
Dame elocuencia para decir lo que debo decir.{zwsp} +
Haz que yo sea el mejor ejemplo para mis hijos.{zwsp} +
Haz que yo sea el mejor amigo de mis amigos.{zwsp} +
Haz de mi un instrumento de tu voluntad.{zwsp} +
Hazme fuerte para recibir los golpes que me da la vida.{zwsp} +
Déjame saber que es lo que tu quieres de mí.{zwsp} +
Déjame tu paz para que la comparta con quien no la tenga.{zwsp} +
Por último, anda conmigo y déjame saber que así es.{zwsp} +
{zwsp} +
*Amén.*

