= Pepe alonso Gospel and Reflections
The items and texts here are from Pepe Alonso.

== Aug.08/2016
En aquel tiempo, se hallaba Jesús con sus discípulos en Galilea y les dijo: “El Hijo del hombre va a ser entregado en manos de los hombres; lo van a matar, pero al tercer día va a resucitar”. Al oír esto, los discípulos se llenaron de tristeza.Cuando llegaron a Cafarnaúm, se acercaron a Pedro los recaudadores del impuesto para el templo y le dijeron: “¿Acaso tu maestro no paga el impuesto?” Él les respondió: “Si lo paga”.Al entrar Pedro en la casa, Jesús se adelantó a preguntarle: “¿Qué te parece, Simón? ¿A quiénes les cobran impuestos los reyes de la tierra, a los hijos o a los extraños?” Pedro le respondió: “A los extraños”. Entonces Jesús le dijo: “Por lo tanto, los hijos están exentos. Pero para no darles motivo de escándalo, ve al lago y echa el anzuelo, saca el primer pez que pique, ábrele la boca y encontrarás una moneda. Tómala y paga por mí y por ti”. Mateo 17, 22 al 27

Jesús murió y resucitó por nosotros. Él, como Dios y Señor, está con nosotros en el camino de la última soledad, en el camino que pasa por el valle de la muerte, en ese camino en el que nadie, más que sólo Él, me puede acompañar. 
El tema de la Resurrección y del juicio final debe influir prácticamente en nuestra vida diaria, nos debe motivar para ordenar nuestra vida presente, porque al final sólo queda lo que hayamos hecho por Dios y por los demás. Recordemos siempre que nuestra opción por la vida eterna se va fraguando cada día. Por eso es tan importante el momento presente para el cristiano, porque aquí nos jugamos lo más importante: nuestra salvación, nuestro destino eterno.
Dios nos concede un tiempo determinado, muy corto, para que le amemos, para que imitemos a su Hijo Jesucristo y para que realicemos nuestra misión en la Iglesia. La vida es el tiempo que tenemos para amar a Dios y al prójimo. Ante la brevedad del tiempo debemos sentir la necesidad de hacer rendir al máximo el espacio que Dios nos concede, alejando de nosotros la pereza, la superficialidad, el materialismo, la desidia.
La fe en el Juicio final y en la Resurrección no deben despertar miedo en nosotros, sino más bien responsabilidad y esperanza, al saber que Dios premiará todo esfuerzo, y al final nos encontraremos con Él si le somos fieles.

*Oremos.*
Jesús, ayúdame a entregar mi vida en el servicio y en el amor a los demás, como Tú lo hiciste.
¡Señor, ayúdame a vivir día a día de manera que me encuentre un día contigo! Amén

== Aug.09/2016
En cierta ocasión, los discípulos se acercaron a Jesús y le preguntaron: “¿Quién es el más grande en el Reino de los cielos?”Jesús llamó a un niño, lo puso en medio de ellos y les dijo: “Yo les aseguro a ustedes que si no cambian y no se hacen como los niños, no entrarán en el Reino de los cielos. Así pues, quien se haga pequeño como este niño, ése es el más grande en el Reino de los cielos. Y el que reciba a un niño como éste en mi nombre, me recibe a mí.Cuidado con despreciar a uno de estos pequeños, pues yo les digo que sus ángeles, en el cielo, ven continuamente el rostro de mi Padre, que está en el cielo.¿Qué les parece? Si un hombre tiene cien ovejas y se le pierde una, ¿acaso no deja las noventa y nueve en los montes, y se va a buscar a la que se le perdió? Y si llega a encontrarla, les aseguro que se alegrará más por ella, que por las noventa y nueve que no se le perdieron. De igual modo el Padre celestial no quiere que se pierda ni uno solo de estos pequeños”.
Mateo 18, 1-5. 10. 12-14

Jesús nos enseña que el más grande en el Reino de los cielos es aquel que se hace como niño. Y es que Dios ama la sencillez. Él mismo se hizo niño. Así reina Dios. Se hace pequeño por nosotros para estar a nuestro alcance y pedirnos nuestro amor. Dios nos enseña así, a amar a los niños, a los pequeños, a los débiles. Nos invita a poner los ojos en los niños que sufren, tanto los nacidos como los no nacidos, en los niños que viven en miseria, en los niños que teniéndolo todo carecen de amor.
El Dios que se ha hecho pequeño nos interpela e invita a aprender a vivir como Él, a practicar la humildad. Nos invita a ser ¡como niños! Pensemos que los niños se refugian en sus padres, solicitan su ayuda y asistencia, se dejan corregir y, además, tienen un corazón puro e inocente, sin maldad en la mente y corazón… 
Así hemos de conducirnos con Dios, hemos de acudir a Él como a un Padre, pedirle su auxilio, pedirle que nos enseñe a ser hijos suyos, hemos de dejarnos educar por Él, evitando toda tendencia hacia el mal y purificando la mente y el corazón, a través de la comunión diaria con el Espíritu Santo.
Recordemos con frecuencia el Amor de Dios. Para Él siempre seremos como niños necesitados de su gracia.

*Oremos.*
Espíritu Santo, dame tu luz en este momento de oración. Con la confianza de un niño pido también la intercesión de mi ángel de la guarda, de modo que tenga la docilidad para escuchar la Palabra y seguirla, como una oveja sigue a su pastor. Amén